
name: Publish Package to npmjs

# On push to master
on:
  push:
    branches: [monorepo]

# Do the job - build
jobs:
  build:
    name: Publish package to npmjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      # - run: npm build
      # - run: npm test
      - run: npm publish-lib-1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}